name: money_tracker_app
description: "A comprehensive money management application built with Flutter, featuring expense tracking, secure Firebase synchronization, offline support with Hive, and insightful financial analytics."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  equatable: ^2.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.4.13
  hive_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/screens/
